version: '3.7'

services:
  mqtt:
    image: mqtt-test-server
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: mqtt-server
    ports:
        - "9001:9001"
        - "1883:1883"
    restart: unless-stopped
    networks:
      - test
    secrets:
      - mqtt_pass
      - mqtt_user

  client:
    image: mqtt-test-client
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: mqtt-client
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - test
    secrets:
      - mqtt_pass
      - mqtt_user

networks:
  test:
    name: test

secrets:
  mqtt_pass:
    file: .mqtt_password
  mqtt_user:
    file: .mqtt_user
