version: '3.7'

services:
  ca:
    image: mqtt-ca
    build:
      context: .
      dockerfile: Dockerfile.ca
    env_file:
      - ca.env 
    hostname: ca
    volumes:
      - "${PWD}/step:/home/step"
    networks:
      test:
          aliases:
            - ca.mqtt.local
    expose:
      - 8051
      - 8050
    secrets:
      - ca_pass

  mqtt:
    image: mqtt-test-server
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: server
    depends_on:
      ca:
        condition: service_healthy
    expose:
      - 8883
    restart: unless-stopped
    networks:
      test:
        aliases:
          - server.mqtt.local
    secrets:
      - mqtt_pass
      - mqtt_user

  client:
    image: mqtt-test-client
    build:
      context: .
      dockerfile: Dockerfile.client
    hostname: client
    depends_on:
      ca:
        condition: service_healthy
    restart: unless-stopped
    networks:
      test:
        aliases:
          - client.mqtt.local
    secrets:
      - mqtt_pass
      - mqtt_user

networks:
  test:
    name: mqtt.local

secrets:
  ca_pass:
    file: .ca_password
  mqtt_pass:
    file: .mqtt_password
  mqtt_user:
    file: .mqtt_user
