FROM smallstep/step-cli as step
FROM efrecon/mqtt-client:latest

#copy step binary for bootstrapping ca
COPY --from=step /usr/local/bin/step /usr/local/bin/


COPY trust_ca.sh .

ENTRYPOINT ["./trust_ca.sh","&&","tail", "-f", "/dev/null"]