FROM smallstep/step-ca

USER root
RUN apk add --update nginx jq
RUN mkdir /static && chown step:step /static && \
    chown -R step:step /var/lib/nginx && \
    chown -R step:step /var/log/nginx && \
    chown -R step:step /run/nginx && \
    chmod +x /entrypoint.sh


USER step
COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./start_ca.sh /
ENTRYPOINT ["/start_ca.sh"]